name: school_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.7
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.1.0
  fluid_bottom_nav_bar: ^1.4.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.1.0
  new_gradient_app_bar: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/


























